#!/usr/bin/env python3
"""Write the frame-screening robustness tables from ``compare_screened_refits.py`` outputs.

Output: ``ScaleF_Overleaf/tables/layout/screening_robustness.tex`` (summary and per-site panels).
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "paper/results/screened_refits"
OUT = ROOT / "ScaleF_Overleaf/tables/layout/screening_robustness.tex"
ARMS = [
    ("confirmatory_v6_masks", "Full-field masks"),
    ("confirmatory_v6_screen", "Screened"),
    ("confirmatory_v6_repl", "Screened + replacements"),
]
SITE_NAMES = {"algard": "{\\AA}lg{\\aa}rd", "amli": "{\\AA}mli", "naerbo": "N{\\ae}rb{\\o}", "tromso": "Troms{\\o}"}


def sgn(x: float, nd: int) -> str:
    return f"${x:+.{nd}f}$"


def ci(c: list[float], nd: int) -> str:
    return f"$[{c[0]:+.{nd}f},{c[1]:+.{nd}f}]$"


def main() -> None:
    comp = {ns: json.loads((RES / f"compare_{ns}.json").read_text()) for ns, _ in ARMS}
    n = comp[ARMS[0][0]]["n_sites"]
    base = comp[ARMS[0][0]]
    lines = [
        "% Generated by scripts/build_screening_table.py; do not edit by hand.",
        "\\begin{table}[H]\\centering\\small",
        "\\caption{Frame-screening robustness on the $17$ named sites (seeds $6/7/8$, configuration and base date of "
        "\\Cref{tab:frozen-17}). \\emph{Full-field masks}: OmniCloudMask class maps computed over the whole LR512 field "
        "replace the screening-window maps; all frames kept. \\emph{Screened}: the same masks, and frames with more than "
        "$15\\%$ thick cloud, thin cloud, or shadow over the field, or more than $10\\%$ of valid pixels with all visible "
        "bands above $0.2$ reflectance, are removed. \\emph{Screened + replacements}: removed frames are replaced by the "
        "next admissible dates under the original ranking and date range. Change against the reported fits (site means, "
        "site-bootstrap 95\\% CI); \\emph{better}: sites where the arm improves on the reported fit. Gain: over bilinear "
        f"(reported: PSNR ${base['psnr']['gain_v5']['mean']:.2f}$~dB, SSIM ${base['ssim']['gain_v5']['mean']:.4f}$, "
        f"LPIPS ${base['lpips']['gain_v5']['mean']:.4f}$).}}",
        "\\label{tab:screening-robustness}",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{adjustbox}{max width=\\linewidth}",
        "\\begin{tabular}{llcccc}\\toprule",
        "Arm & Metric & Change & 95\\% CI & Better & Gain over bilinear (sites) \\\\ \\midrule",
    ]
    for i, (ns, label) in enumerate(ARMS):
        c = comp[ns]
        for m, name, nd in (("psnr", "PSNR (dB)", 2), ("ssim", "SSIM", 4), ("lpips", "LPIPS", 4)):
            d = c[m]["delta"]
            g = c[m]["gain_screen"]
            lines.append(f"{label if m == 'psnr' else ''} & {name} & {sgn(d['mean'], nd)} & {ci(d['ci95'], nd)} & "
                         f"{d['n_sites_better']}/{n} & {sgn(g['mean'], nd)} ({g['n_sites_improved']}/{n}) \\\\")
        if i < len(ARMS) - 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule\\end{tabular}", "\\end{adjustbox}\\end{table}", ""]

    ps = {ns: comp[ns]["per_site"] for ns, _ in ARMS}
    lines += [
        "\\begin{table}[H]\\centering\\small",
        "\\caption{Per-site frame counts, PSNR (dB), and LPIPS for the arms of \\Cref{tab:screening-robustness} (means "
        "over seeds $6/7/8$). Frames: reported / after screening / after replacement.}",
        "\\label{tab:screening-sites}",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{adjustbox}{max width=\\linewidth}",
        "\\begin{tabular}{lccccccccc}\\toprule",
        " & & \\multicolumn{4}{c}{PSNR} & \\multicolumn{4}{c}{LPIPS} \\\\ \\cmidrule(lr){3-6}\\cmidrule(lr){7-10}",
        "Site & Frames & Reported & Masks & Screened & + repl. & Reported & Masks & Screened & + repl. \\\\ \\midrule",
    ]
    for s in sorted(ps[ARMS[0][0]]):
        a, b, r = ps["confirmatory_v6_masks"][s], ps["confirmatory_v6_screen"][s], ps["confirmatory_v6_repl"][s]
        name = SITE_NAMES.get(s, s.capitalize())
        lines.append(
            f"{name} & {a['n_frames_v5']}/{b['n_frames']}/{r['n_frames']} & {a['psnr']['v5']:.2f} & {a['psnr']['screen']:.2f} & "
            f"{b['psnr']['screen']:.2f} & {r['psnr']['screen']:.2f} & {a['lpips']['v5']:.3f} & {a['lpips']['screen']:.3f} & "
            f"{b['lpips']['screen']:.3f} & {r['lpips']['screen']:.3f} \\\\")
    lines += ["\\bottomrule\\end{tabular}", "\\end{adjustbox}\\end{table}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
