#!/usr/bin/env python3
"""Per-site complete-field table from ``complete_fields_v2.json`` (masked metrics, surface reflectance)."""
from __future__ import annotations

import argparse
import collections
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
TEX_NAMES = {
    "tromso": r"Troms{\o}", "naerbo": r"N{\ae}rb{\o}", "algard": r"{\AA}lg{\aa}rd", "amli": r"{\AA}mli",
}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path, default=ROOT / "paper/results/complete_fields_v2.json")
    ap.add_argument("--out", type=Path, default=ROOT / "ScaleF_Overleaf/tables/layout/complete_tiles.tex")
    args = ap.parse_args()
    rows = json.loads(args.src.read_text())["rows"]
    by = collections.defaultdict(list)
    for r in rows:
        by[r["city"]].append(r)

    def arr(rs, k):
        return np.array([r[k] for r in rs], dtype=float)

    lp_gain = arr(rows, "lpips_bilinear") - arr(rows, "lpips_model")
    ps_gain = arr(rows, "psnr_model") - arr(rows, "psnr_bilinear")
    ss_gain = arr(rows, "ssim_model") - arr(rows, "ssim_bilinear")
    body = []
    for city, rs in sorted(by.items(), key=lambda kv: arr(kv[1], "lpips_model").mean()):
        lm, lb = arr(rs, "lpips_model").mean(), arr(rs, "lpips_bilinear").mean()
        body.append(
            f"    {TEX_NAMES.get(city, city.capitalize())} & {len(rs)} & {lm:.4f} & {lb:.4f} & {lb - lm:+.4f}"
            f" & {(arr(rs, 'psnr_model') - arr(rs, 'psnr_bilinear')).mean():+.2f}"
            f" & {(arr(rs, 'ssim_model') - arr(rs, 'ssim_bilinear')).mean():+.3f}"
            f" & {arr(rs, 'time_s').mean():.0f} \\\\"
        )
    n = len(rows)
    caption = (
        r"Selected $4{\times}128^2$ update configuration on complete $5.12\,\mathrm{km}$ fields "
        r"(blur halo, LR-only stopping with patience~$8$, seed~$6$), each scored under its own LR512 correction "
        r"shared with bilinear. Scoring protocol as for the named sites: floating-point outputs in surface "
        r"reflectance (offset removed) with masked SSIM and LPIPS. "
        f"Means per site; overall LPIPS ${arr(rows, 'lpips_model').mean():.3f}$ against "
        f"${arr(rows, 'lpips_bilinear').mean():.3f}$ for bilinear, gain ${lp_gain.mean():+.3f}$ "
        f"(${int((lp_gain > 0).sum())}/{n}$ fields improved); PSNR gain ${ps_gain.mean():+.2f}$~dB "
        f"(${int((ps_gain > 0).sum())}/{n}$); SSIM gain ${ss_gain.mean():+.3f}$ (${int((ss_gain > 0).sum())}/{n}$)."
    )
    tex = "\n".join([
        f"% Generated by scripts/build_complete_tiles_table.py from {args.src.relative_to(ROOT)}.",
        r"\begin{table}[H]",
        r"  \centering",
        f"  \\caption{{{caption}}}",
        r"  \label{tab:complete-tiles}",
        r"  \footnotesize",
        r"  \setlength{\tabcolsep}{4pt}",
        r"  \begin{adjustbox}{max width=\linewidth}",
        r"\begin{tabular}{lrrrrrrr}",
        r"    \toprule",
        r"    Site & $n$ & LPIPS $\downarrow$ & Bilinear & Gain & $\Delta$PSNR (dB) & $\Delta$SSIM & Time (s) \\",
        r"    \midrule",
        *body,
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{adjustbox}",
        r"\end{table}",
        "",
    ])
    args.out.write_text(tex)
    print(caption)


if __name__ == "__main__":
    main()
