#!/usr/bin/env python3
"""Render ``paper/results/hash_encoding_audit.json`` as a LaTeX table."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "paper/results/hash_encoding_audit.json"
OUT = ROOT / "ScaleF_Overleaf/generated/tables/hash_encoding_audit.tex"


def main() -> None:
    audit = json.loads(SRC.read_text())
    fz = audit["frozen_settings"]
    T = 1 << fz["hash_log2_hashmap_size"]
    rows = []
    for s in audit["sides"]:
        lv = s["levels"]
        hashed = [x["resolution"] for x in lv if x["indexing"] == "hash"]
        eq = s["dense_equivalence"]
        eq_txt = "identical" if eq and eq.get("max_abs_feature_diff") == 0.0 else "\\textemdash"
        rows.append(
            f"    LR{s['lr_side']} & ${lv[0]['resolution']}$--${lv[-1]['resolution']}$ & "
            f"${lv[0]['cell_m_at_10m_gsd']:.0f}$--${lv[-1]['cell_m_at_10m_gsd']:.0f}$ & "
            f"{s['n_dense_levels']}/{s['n_hashed_levels']} & "
            f"{s['encoder_params_actual'] / 1e6:.3f} & "
            f"{s['encoder_params_actual'] / s['encoder_params_if_all_levels_full_table'] * 100:.1f} & "
            f"{eq_txt} \\\\"
            + ("" if not hashed else f" % hashed resolutions {hashed}")
        )
    lines = [
        "% AUTO-GENERATED by scripts/build_hash_audit_table.py; DO NOT EDIT.",
        "\\begin{table}[t]",
        "  \\centering",
        "  \\caption{Grid-encoding layout realised by tiny-cuda-nn at the frozen settings "
        f"(${fz['hash_n_levels']}$ levels, ${fz['hash_n_features_per_level']}$ features, "
        f"table $2^{{{fz['hash_log2_hashmap_size']}}}={T:,}$ entries per level, finest level at the LR grid). "
        "A level is indexed densely when its $(\\text{resolution})^2$ vertices fit the table. "
        "Parameters are encoder entries$\\times$features; `Full' is the share of a fully allocated table. "
        "Dense check: the same parameters loaded into a dense tiny-cuda-nn grid give bitwise-identical features "
        "on $2^{20}$ random coordinates.}",
        "  \\label{tab:hash-audit}",
        "  \\footnotesize",
        "  \\begin{tabular}{lcccrrc}",
        "    \\toprule",
        "    Field & Resolution & Cell (m) & Dense/hashed & Params (M) & Full (\\%) & Dense check \\\\",
        "    \\midrule",
        *rows,
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
    ]
    OUT.write_text("\n".join(lines).replace(f"{T:,}", f"{T:,}".replace(",", "{,}")))
    print(OUT)


if __name__ == "__main__":
    main()
